- platform: mqtt
  name: "Plugwise Server"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F00002365FE'
  state_topic: 'plugwise2py/state/circle/000D6F00002365FE'
  value_template: '{"mac": "000D6F00002365FE", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F00002365FE", "switch": "on"}'
  payload_off: '{"mac": "000D6F00002365FE", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise Koelkast"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F0000236997'
  state_topic: 'plugwise2py/state/circle/000D6F0000236997'
  value_template: '{"mac": "000D6F0000236997", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F0000236997", "switch": "on"}'
  payload_off: '{"mac": "000D6F0000236997", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise Keuken"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F0000236A41'
  state_topic: 'plugwise2py/state/circle/000D6F0000236997'
  value_template: '{"mac": "000D6F0000236997", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F0000236997", "switch": "on"}'
  payload_off: '{"mac": "000D6F0000236997", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise TV"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F0000236385'
  state_topic: 'plugwise2py/state/circle/000D6F0000236385'
  value_template: '{"mac": "000D6F0000236385", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F0000236385", "switch": "on"}'
  payload_off: '{"mac": "000D6F0000236385", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise Lamp"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F00002372B2'
  state_topic: 'plugwise2py/state/circle/000D6F00002372B2'
  value_template: '{"mac": "000D6F00002372B2", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F00002372B2", "switch": "on"}'
  payload_off: '{"mac": "000D6F00002372B2", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise Zonnepaneel Rechts"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F000023725F'
  state_topic: 'plugwise2py/state/circle/000D6F000023725F'
  value_template: '{"mac": "000D6F000023725F", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F000023725F", "switch": "on"}'
  payload_off: '{"mac": "000D6F000023725F", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise Zonnepaneel Links"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F00002362A6'
  state_topic: 'plugwise2py/state/circle/000D6F00002362A6'
  value_template: '{{ value_json.switch }}'
  payload_on: '{"mac": "000D6F00002362A6", "switch": "on"}'
  payload_off: '{"mac": "000D6F00002362A6", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise CV"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F0000236D2F'
  state_topic: 'plugwise2py/state/circle/000D6F0000236D2F'
  state_template: '{{ value_json.switch }}'
  payload_on: '{"mac": "000D6F0000236D2F", "switch": "on"}'
  payload_off: '{"mac": "000D6F0000236D2F", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise Mechanische Ventilatie"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F00002369B9'
  state_topic: 'plugwise2py/state/circle/000D6F00002369B9'
  value_template: '{"mac": "000D6F00002369B9", "switch": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F00002369B9", "switch": "on"}'
  payload_off: '{"mac": "000D6F00002369B9", "switch": "off"}'
  retain: true
- platform: mqtt
  name: "Plugwise Lamp Buffetkast"
  optimistic : false
  command_topic: 'plugwise2py/cmd/switch/000D6F0000237228'
  state_topic: 'plugwise2py/state/circle/000D6F0000237228'
  value_template: '{"mac": "000D6F0000237228", "cmd": "switch", "val": "{{ value_json.switch }}"}'
  payload_on: '{"mac": "000D6F0000237228", "cmd": "switch", "val": "on"}'
  payload_off: '{"mac": "000D6F0000237228", "cmd": "switch", "val": "off"}'
  retain: true
