- id: livingroomlightson
  alias: Living room lights on 45 mins before sunset
  trigger:
    platform: sun
    event: sunset
    offset: -00:45:00
  action:
    service: homeassistant.turn_on
    entity_id: group.living_room
- id: livingroomlightsoff
  alias: Living room lights off at 1am
  trigger:
    platform: time
    at: 01:00:00
  action:
    service: homeassistant.turn_off
    entity_id: group.living_room
- id: alarm
  alias: 'alarm: Notify state changes'
  hide_entity: true
  trigger:
  - entity_id: alarm_control_panel.alarm
    platform: state
  action:
  - data_template:
      message: Alarm changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state
        }}
    service: notify.telegram
- id: lights_toilet_off
  alias: 'Toilet: lights off after 30 seconds no motion'
  trigger:
  - entity_id: binary_sensor.toilet_motion_sensor
    for:
      seconds: 30
    platform: state
    to: 'off'
  action:
  - entity_id: switch.lamp_toilet_switch
    service: homeassistant.turn_off
- id: lights_toilet_on
  alias: 'Toilet: Turn on light based on motion'
  trigger:
  - entity_id: binary_sensor.toilet_motion_sensor
    platform: state
    to: 'on'
  action:
  - entity_id: switch.lamp_toilet_switch
    service: homeassistant.turn_on
- id: lights_wouter_off
  alias: 'Kamer wouter: lights off after 5 minutes no motion'
  trigger:
  - entity_id: binary_sensor.aeotec_dsb05_multisensor_sensor
    platform: state
    to: 'off'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: light.lamp_wouter_level
- id: owntracks_refresh
  alias: Owntracks Refresh
  trigger:
    platform: time
    minutes: /15
    seconds: 0
  action:
    service: script.refresh_devices
- id: updates
  alias: Update Available Notifications
  trigger:
  - entity_id: updater.updater
    platform: state
  action:
  - data:
      message: Home Assistant {{ states.updater.updater.state }} is now available.
    service: notify.telegram
- id: battery_low
  alias: Battery low
  trigger:
    platform: state
    entity_id: sensor.oregontemphygro_2c75_bat, sensor.oregontemphygro_2ccc_bat, sensor.oregontemphygro_2cec_bat,
      sensor.oregontemphygro_cc7a_bat
    to: low
  action:
    service: notify.telegram
    data:
      message: Battery of {{ trigger.entity_id }} low!
- id: battery_below_10
  alias: battery level below 10%
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_dsb05_battery, sensor.benext_dhszwsnmt01_multi_sensor_battery,
      sensor.benext_door_sensor_battery, sensor.benext_molite_sensor_battery, sensor.toilet_motion_battery,
      sensor.watersensor_vaatwasser_battery, sensor.watersensor_wasmachine_battery
    below: 11
  action:
    service: notify.telegram
    data:
      message: Battery of {{ trigger.entity_id }} low!
