
# When we detect power being drawn from the dishwasher,
# mark the dishwasher as using power

- alias: Set dishwasher active when power detected
  trigger:
    - platform: numeric_state
      entity_id: sensor.dishwasher_power
      above: 10
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Dirty
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Clean
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Running

# When the power level drops below 10, and the Dishwasher is set to
# the 'Running' state, mark the Dishwasher as Finished

- alias: Set dishwasher drying when power drops
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_smart_energy_switch_power_16_8
      below: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Drying

# Once the dishwasher status has been 'Drying' for 30 minutes, mark the
# dishwasher as clean

- alias: Set dishwasher clean
  trigger:
    - platform: state
      entity_id: input_select.dishwasher_status
      to: Drying
      for:
        minutes: 15
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Clean

# When the power drops and the dishwasher is Clean or Drying, someone has
# turned the Dishwasher off and emptied it. We should do this when the state
# of the Dishwasher is clean or Finishing, just incase someone opens the
# Dishwasher before the 30 minute timeout has been reached.

- alias: Set Dishwasher dirty when power off
  trigger:
    - platform: numeric_state
      entity_id: sensor.aeotec_smart_energy_switch_power_16_8
      below: 1
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.aeotec_smart_energy_switch_power_16_8
        below: 1
      - condition: or
        conditions:
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Clean
        - condition: state
          entity_id: input_select.dishwasher_status
          state: Drying
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.dishwasher_status
        option: Dirty
- id: livingroomlightson
  alias: Living room lights on 45 mins before sunset
  trigger:
    platform: sun
    event: sunset
    offset: -00:45:00
  action:
    service: homeassistant.turn_on
    entity_id: group.living_room
- id: livingroomlightsoff
  alias: Living room lights off at 1am
  trigger:
    platform: time
    at: 01:00:00
  action:
    service: homeassistant.turn_off
    entity_id: group.living_room
- id: updates
  alias: Update Available Notifications
  trigger:
  - entity_id: updater.updater
    platform: state
  action:
  - data:
      message: Home Assistant {{ states.updater.updater.state }} is now available.
    service: notify.telegram
