- id: alarm
  alias: 'alarm: Notify state changes'
  hide_entity: true
  trigger:
  - entity_id: alarm_control_panel.alarm
    platform: state
  action:
  - data_template:
      message: Alarm changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state
        }}
    service: notify.telegram
- id: lights_toilet_off
  alias: 'Toilet: lights off after 30 seconds no motion'
  trigger:
  - entity_id: binary_sensor.toilet_motion_sensor_21_0
    for:
      seconds: 30
    from: 'on'
    platform: state
    state: 'off'
    to: 'off'
  action:
  - entity_id: switch.lamp_toilet_switch_20_0
    service: homeassistant.turn_off
- id: lights_toilet_on
  alias: 'Toilet: Turn on light based on motion'
  trigger:
  - entity_id: binary_sensor.toilet_motion_sensor_21_0
    from: 'off'
    platform: state
    state: 'on'
    to: 'on'
  action:
  - entity_id: switch.lamp_toilet_switch_20_0
    service: homeassistant.turn_on
- id: lights_wouter_off
  alias: 'Kamer wouter: lights off after 5 minutes no motion'
  trigger:
    platform: state
    entity_id: binary_sensor.aeotec_dsb05_multisensor_sensor_6_0
    state: 'off'
    for:
      minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: light.lamp_wouter_level_17_0
- id: lights_wouter
  alias: 'Kamer wouter: Turn on lights based on motion and lux values'
  trigger:
  - entity_id: binary_sensor.aeotec_dsb05_multisensor_sensor_6_0
    from: 'off'
    platform: state
    state: 'on'
    to: 'on'
  - below: 10
    entity_id: sensor.aeotec_dsb05_multisensor_luminance_6_3
    platform: numeric_state
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.aeotec_dsb05_multisensor_sensor_6_0
      state: 'on'
    - below: 10
      condition: numeric_state
      entity_id: sensor.aeotec_dsb05_multisensor_luminance_6_3
  action:
  - entity_id: light.lamp_wouter_level_17_0
    service: homeassistant.turn_on
- id: owntracks_refresh
  alias: Owntracks Refresh
  trigger:
    platform: time
    minutes: /15
    seconds: 0
  action:
    service: script.refresh_devices
- id: updates
  alias: Update Available Notifications
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.telegram
    data:
      message: "Home Assistant {{ states.updater.updater.state }} is now available."
- id: battery_low
  alias: Battery low
  trigger:
    platform: state
    entity_id: sensor.oregontemphygro_2c75_bat, sensor.oregontemphygro_2ccc_bat, sensor.oregontemphygro_2cec_bat, sensor.oregontemphygro_cc7a_bat
    to: low
  action:
    service: notify.telegram
    data:
      message: "Battery of {{ trigger.entity_id }} low!"
- id: battery_below_10
  alias: battery level below 10%
  trigger:
    platform: numeric_state
    entity_id: sensor.aeotec_dsb05_battery, sensor.benext_dhszwsnmt01_multi_sensor_battery, sensor.benext_door_sensor_battery, sensor.benext_molite_sensor_battery, sensor.toilet_motion_battery, sensor.watersensor_vaatwasser_battery, sensor.watersensor_wasmachine_battery
    below: 11
  action:
    service: notify.telegram
    data:
      message: "Battery of {{ trigger.entity_id }} low!"