#- platform: mjpeg
#  mjpeg_url: http://192.168.1.112:10010/videostream.cgi
#  name: Front Door
#  username: !secret camera_username
#  password: !secret camera_password
###CAMERA 2
#- platform: mjpeg
#  mjpeg_url: http://192.168.1.123:10001/videostream.cgi
#  name: Porch
#  username: !secret camera_username
#  password: !secret camera_password 
- platform: generic
  name: Wouter
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{states.device_tracker.owntracks_iphone_wouter.attributes.latitude}},{{states.device_tracker.owntracks_iphone_wouter.attributes.longitude}}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:W%7C{{states.device_tracker.owntracks_iphone_wouter.attributes.latitude}},{{states.device_tracker.owntracks_iphone_wouter.attributes.longitude}}
  limit_refetch_to_url_change: true