homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.357958
  longitude: 4.780472
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  trusted_networks:
    - 127.0.0.1/32
    - 192.168.16.0/24

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.date
      - sensor.date__time
      - sensor.time
      - sensor.time__date

logger:
  default: info

automation: !include automations.yaml
camera: !include cameras.yaml
group: !include groups.yaml
sensor: !include_dir_merge_list sensors/
script: !include_dir_named scripts/

# log everything to influxdb for historical graphs
#influxdb:
#  host: 127.0.0.1
#  username: hass
#  password: !secret influxdb_password

# Track the sun
sun:

climate:
  platform: toon
  name: Toon Thermostat
  host: 192.168.16.16
  port: 10080
#  scan_interval: 10
  
# MQTT setup
mqtt:
  broker: 192.168.16.5
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  protocol: 3.1


# Example configuration.yaml entry
notify: !include notify.yaml

# Owntracks configuration
device_tracker:
  - platform: owntracks
  - platform: fritz
  - platform: aruba
    host: 192.168.16.40
    username: !secret aruba_username
    password: !secret aruba_password
  
# OpenZWave
zwave:
  usb_path: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  device_config: !include zwave_device_config.yaml
  
# RFXCom
rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1Y0QAVS-if00-port0
  debug: true
  
# Yamaha receiver
media_player:
  - platform: yamaha
# Sony TV with Android
  - platform: cast
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

#homematic:
#  hosts:
#    wireless:
#      ip: 127.0.0.1
#      resolvenames: metadata

shell_command: !include shell_commands.yaml

switch:
  platform: rfxtrx
  automatic_add: true
  
light:
  - platform: rfxtrx
    automatic_add: true
  - platform: hue
    host: 192.168.16.26

zone: !include zones.yaml
weblink: !include weblinks.yaml

config:

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_95432313837351C061B2-if00
  
telegram_bot:
  platform: webhooks
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id
