automation: !include automations.yaml
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include config/cameras.yaml
climate: !include config/climate.yaml
device_tracker: !include config/device_tracker.yaml
fan: !include config/fan.yaml
ffmpeg: !include config/ffmpeg.yaml
group: !include groups.yaml
homeassistant: !include config/homeassistant.yaml
homekit: !include config/homekit.yaml
#homematic: !include config/homematic.yaml
http: !include config/http.yaml
#input_select: !include config/input_select.yaml
ios:
light: !include config/light.yaml
logbook: !include config/logbook.yaml
mycroft: !include config/mycroft.yaml
media_player: !include config/media_player.yaml
mqtt: !include config/mqtt.yaml
notify: !include notify.yaml
panel_custom: !include config/panel_custom.yaml
rflink: !include config/rflink.yaml
rfxtrx: !include config/rfxtrx.yaml
script: !include_dir_named scripts/
sensor: !include_dir_merge_list sensors/
shell_command: !include config/shell_commands.yaml
switch: !include_dir_merge_list switches/
telegram_bot: !include config/telegram_bot.yaml
vacuum: !include config/vacuum.yaml
weblink: !include weblinks.yaml
zone: !include zones.yaml
zwave: !include config/zwave.yaml

config:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

logger:
  default: warning
  logs:
    homeassistant.components.http.ban: warning

# log everything to influxdb for historical graphs
influxdb:
  host: 127.0.0.1
  username: home_assistant
  password: !secret influxdb_password

# Track the sun
sun:

recorder:
  purge_interval: 2
  purge_keep_days: 7
  
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: 'http://192.168.16.5:1880/'