automation: !include automations.yaml
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include cameras.yaml
climate: !include config/climate.yaml
device_tracker: !include config/device_tracker.yaml
ffmpeg: !include config/ffmpeg.yaml
group: !include groups.yaml
homeassistant: !include config/homeassistant.yaml
#homematic: !include config/homematic.yaml
http: !include config/http.yaml
light: !include config/light.yaml
logbook: !include config/logbook.yaml
media_player: !include config/media_player.yaml
mqtt: !include config/mqtt.yaml
notify: !include notify.yaml
panel_custom: !include config/panel_custom.yaml
rflink: !include config/rflink.yaml
rfxtrx: !include config/rfxtrx.yaml
script: !include_dir_named scripts/
sensor: !include_dir_merge_list sensors/
shell_command: !include shell_commands.yaml
switch: !include_dir_merge_list switches/
telegram_bot: !include config/telegram_bot.yaml
vacuum: !include config/vacuum.yaml
weblink: !include weblinks.yaml
zone: !include zones.yaml
zwave: !include config/zwave.yaml

config:

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

logger:
  default: info

# log everything to influxdb for historical graphs
#influxdb:
#  host: 127.0.0.1
#  username: hass
#  password: !secret influxdb_password

# Track the sun
sun:
