- platform: template
  sensors:
    benext_dhszwsnmt01_multi_sensor_battery:
      value_template: >-
        {%- if states.zwave.benext_dhszwsnmt01_multi_sensor -%}
          {{ states.zwave.benext_dhszwsnmt01_multi_sensor.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.benext_dhszwsnmt01_multi_sensor
    aeotec_dsb05_battery:
      value_template: >-
        {%- if states.zwave.aeotec_dsb05_multisensor -%}
          {{ states.zwave.aeotec_dsb05_multisensor.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.aeotec_dsb05_multisensor
    benext_door_sensor_battery:
      value_template: >-
        {%- if states.zwave.benext_door_sensor -%}
          {{ states.zwave.benext_door_sensor.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.benext_door_sensor
    benext_molite_sensor_battery:
      value_template: >-
        {%- if states.zwave.benext_molite_sensor -%}
          {{ states.zwave.benext_molite_sensor.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.benext_molite_sensor
    toilet_motion_battery:
      value_template: >-
        {%- if states.zwave.toilet_motion -%}
          {{ states.zwave.toilet_motion.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.toilet_motion
    watersensor_vaatwasser_battery:
      value_template: >-
        {%- if states.zwave.watersensor_vaatwasser -%}
          {{ states.zwave.watersensor_vaatwasser.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.watersensor_vaatwasser
    watersensor_wasmachine_battery:
      value_template: >-
        {%- if states.zwave.watersensor_wasmachine -%}
          {{ states.zwave.watersensor_wasmachine.attributes.battery_level }}
        {%- else -%}
          n/a
        {%- endif -%}
      unit_of_measurement: '%'
      entity_id: zwave.watersensor_wasmachine
