- platform: command_line
  name: systemstate_homebridge
  scan_interval: 10
  command: if pgrep -x "homebridge" > /dev/null; then echo Online; else echo Offline; fi
  payload_on: "Online"
  payload_off: "Offline"
  device_class: connectivity