- platform: command_line
  name: systemstate_mosquitto
  scan_interval: 10
  command: if pgrep -xa "mosquitto" > /dev/null; then echo Online; else echo Offline; fi
  payload_on: "Online"
  payload_off: "Offline"
  device_class: connectivity