name: Floorplan BG
image: /local/custom_ui/floorplan/p16.svg
stylesheet: /local/custom_ui/floorplan/floorplan.css

warnings:

#pan_zoom:

date_format: DD-MMM-YYYY

groups:
- name: Binary Sensors
  entities:
    - binary_sensor.toilet_motion_sensor
  states:
    - state: 'off'
      class: 'motion-off'
    - state: 'on'
      class: 'motion-on'
  state_transitions:
    - name: On to off
      from_state: 'on'
      to_state: 'off'
      duration: 2
    - name: Off to on
      from_state: 'off'
      to_state: 'on'
      duration: 1
- name: Temperature
  entities:
    - sensor.vair_sensor_1_temperature
    - sensor.vair_sensor_2_temperature
    - sensor.toilet_motion_temperature
    - sensor.oregontemphygro_2c40_temp
    - sensor.oregontemphygro_2c75_temp
    - sensor.oregontemphygro_2ccc_temp
    - sensor.oregontemphygro_cc7a_temp
    - sensor.mcthings_doorsensor_1_temperature
  text_template: '${entity.state ? entity.state + "°C" : "undefined"}'
  class_template: 'return "static-text";'
- name: Humidity
  entities:
    - sensor.oregontemphygro_2c40_hum
    - sensor.oregontemphygro_2c75_hum
    - sensor.oregontemphygro_2ccc_hum
    - sensor.oregontemphygro_cc7a_hum
  text_template: '${entity.state ? entity.state + "%" : "undefined"}'
  class_template: 'return "static-text";'
- name: Lights
  entities:
    - light.lamp_gang_level
    - light.lamp_tv
    - light.woonkamer_lamp
    - light.lamp_wouter_level
  states:
    - state: 'on'
      class: 'light-on'
    - state: 'off'
      class: 'light-off'
- name: switch
  entities:
    - switch.lamp_boekenkast_switch
    - switch.lamp_toilet_switch
  states:
    - state: 'on'
      class: 'light-on'
    - state: 'off'
      class: 'light-off'
