#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  trusted_networks:
    - 127.0.0.1/32
    - 192.168.16.0/24
