  broker: 192.168.16.5
  port: 1883
  client_id: home-assistant-1
  discovery: true
  discovery_prefix: homeassistant
#  keepalive: 60
#  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
