  nodered:
    title: Node-Red
    icon: mdi:sitemap
    url: https://192.168.16.5:1880
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: http://192.168.16.5:8988
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: http://192.168.16.5:3000