  db_url: !secret recorder_url
  exclude:
    domains:
      - weblink
      - group
      - history_graph
      - sun
    entities:
      - binary_sensor.remote2_motion
      - sensor.date
      - sensor.date_time
      - sensor.internet_time
      - sensor.load_1m
      - sensor.time
      - sensor.time_date
      - sensor.time_utc
