  device:
    type: ethernet
    host: '192.168.16.39'
    port: 10628
  motion_off: 120
  language: 'EN'
  force_standard: 'no'
  sync_time: 'yes'
  allow_remote_arm: 'yes'
  allow_remote_disarm: 'yes'
#  override_code: '1234'
#  arm_without_usercode: 'yes'
